// Code generated by font/bitmap/convert.go; DO NOT EDIT.

package comfortaa

import (
	_ "embed"
	"seedetcher.com/font/bitmap"
	"unsafe"
)

var Bold17 = bitmap.NewFace(unsafe.Slice(unsafe.StringData(dataBold17), len(dataBold17)))
var dataBold17 string
