// Code generated by font/vector/convert.go; DO NOT EDIT.
package main

import (
	_ "embed"
	"seedetcher.com/font/vector"
	"unsafe"
)

var Font = vector.NewFace(unsafe.Slice(unsafe.StringData(bold17Data), len(bold17Data)))

//go:embed bold17.bin
var bold17Data string
